// vite.config.ts
//
// Vite + Vitest config. Adds the PUBLIC_ env prefix and scopes the
// frontend test run to src/.

import fs from "node:fs";
import path from "node:path";
import { defineConfig, type Plugin } from "vitest/config";
import react from "@vitejs/plugin-react";

const RESTAURANT_COUNT_TOKEN = "%RESTAURANT_COUNT%";
// Last known-good count, used only if dashboard-meta.json hasn't been
// generated yet (e.g. `vite dev`/`vite build` run without the pipeline step).
const RESTAURANT_COUNT_FALLBACK = 30_600;

// index.html's SEO copy embeds the restaurant count as a rounded figure
// ("roughly N") so it stays accurate without hand-editing on every
// dataset refresh. dashboard-meta.json is generated by
// pipeline/fetch-inspection.mjs, which always runs before this build.
function injectRestaurantCount(): Plugin {
  return {
    name: "inject-restaurant-count",
    transformIndexHtml(html) {
      let count = RESTAURANT_COUNT_FALLBACK;

      try {
        const metaPath = path.resolve(process.cwd(), "public/data/dashboard-meta.json");
        const meta = JSON.parse(fs.readFileSync(metaPath, "utf-8"));

        if (typeof meta.restaurantCount === "number") {
          count = Math.round(meta.restaurantCount / 100) * 100;
        }
      } catch {
        // Not generated yet — fall back to the last known-good count.
      }

      return html.replaceAll(RESTAURANT_COUNT_TOKEN, count.toLocaleString("en-US"));
    },
  };
}

export default defineConfig({
  plugins: [react(), injectRestaurantCount()],
  // Vite only exposes client-side env vars to import.meta.env when
  // prefixed VITE_ by default. PUBLIC_ARCGIS_API_KEY (read in
  // MapView.tsx) uses a PUBLIC_ prefix instead, so it's added here
  // explicitly to keep it exposed.
  envPrefix: ["VITE_", "PUBLIC_"],
  build: {
    // Emit source maps for the production bundle. They aren't downloaded
    // by browsers unless devtools is open, so there's no user-facing
    // cost, but they make production stack traces and Lighthouse's
    // bundle analysis usable.
    sourcemap: true,
  },
  test: {
    // Scoped to src/ only; pipeline/*.test.mjs is its own suite, run
    // separately via `npm run test:pipeline` (node:test), not picked up here.
    include: ["src/**/*.test.{ts,tsx}"],
  },
});